### ISSUE TITLE
Syncing among devices: one main private key or one per device?

### ISSUE THREAD

**Issue by canadaduane** [stamp-protocol/tracker#22]
If I have a "personal cloud" of devices, e.g. a desktop, an HP laptop, an ipad, and an android phone, would all devices hold a single private key, or would there be a unique private key for each device?

Some situations I'm thinking about:
- my laptop is stolen; does this mean my entire identity is at risk, or can several devices vote to "disable" the stolen (laptop) part of my identity?
- levels of consent: suppose I consider my phone a "less secure" device than my desktop computer (perhaps because I carry the phone around and it could get lost). Is there a way to require that a "more secure" device be involved in a stamp/decision? Or as another example, when assigning ownership of my house as part of a transaction, I want to be really careful, like a nuclear missile has two keys that have to both be turned on within a certain window of time.

**Comment by orthecreedence** [comment]
> If I have a "personal cloud" of devices, e.g. a desktop, an HP laptop, an ipad, and an android phone, would all devices hold a single private key, or would there be a unique private key for each device?

There are three possible private keys involved in this:

- The private key(s) that make up the identity itself, which are used to sign changes to the identity.
- The master key, which is generated via a passphrase you type when loading private/encrypted data from the identity
- The keypair the client uses when communicating with other clients on the StampNet storage network.

As it's planned now, Stamp stores the identity, encrypted, via your master passphrase and when synced via StampNet, all devices would have the *same* representation of the identity. The only private keys that would be different are the communication keys the StampNet clients use to talk to each other. When the identity does sync, it's the same on each device (including the master passphrase).

> my laptop is stolen; does this mean my entire identity is at risk, or can several devices vote to "disable" the stolen (laptop) part of my identity?

Your identity is still protected via your master passphrase, which must be cracked in order to decrypt the private portions of your identity. If you choose a long enough master passphrase, your identity is effectively protected. In the current implementation, the decrypted identity is never tored on disk, and only exists in memory.

> levels of consent: suppose I consider my phone a "less secure" device than my desktop computer (perhaps because I carry the phone around and it could get lost). Is there a way to require that a "more secure" device be involved in a stamp/decision?

So while this isn't built into the implementation as it stands now, I've been thinking something similar. Each transaction in the DAG that makes up the identity holds both a public portion of data and a private portion. The private data for each transaction can be removed/forgotten, which means on your phone, it could be possible to "delete" various private keys (alpha/policy/publish/root) so even if the phone was compromised *and* the identity was unlocked, the attacker would only get access to a subset of the identity.

I'd even say this could be built into StampNet so that your more secure devices *never send* the private keys to your phone at all. And if the attacker tried to request those private keys before you could blacklist the device, your other devices would just ignore it.

I think this is worth a ticket of its own.

> Or as another example, when assigning ownership of my house as part of a transaction, I want to be really careful, like a nuclear missile has two keys that have to both be turned on within a certain window of time.

I think whatever system you'd use to sign over your house would have to be set up as a multisig, and then you could store different private keys on different devices using the syncing logic from above. Then you'd need both your laptop and your phone to sign your house over.

**Comment by orthecreedence** [comment]
BTW created ticket #23 as a place to discuss your "levels of consent" via the syncing protocol, although we can continue the discussion here as well!

**Comment by canadaduane** [comment]
Cool, thanks for the detailed response. I have another question but I will open it as a separate thread.
